### ISSUE TITLE
Add support for SDK 46

### ISSUE THREAD

**Issue by julste** [expo/config-plugins#113]
### Summary

It looks like react native pdf config plugin doesn't work with SDK 46.

### Config Plugin

@config-plugins/react-native-pdf

### What platform(s) does this occur on?

Android, iOS

### SDK Version

46

### Reproducible demo

using:
`expo-cli doctor --fix-dependencies`

results in:
`Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
  (for more info, run: npm why @expo/config-plugins)
`

using: 
`npm ls @expo/config-plugins`

results in:
`├─┬ @config-plugins/react-native-blob-util@0.0.0
│ └── @expo/config-plugins@4.1.5
├─┬ @config-plugins/react-native-pdf@0.0.0
│ └── @expo/config-plugins@4.1.5
`

**Comment by gerwim** [comment]
There are multiple projects not working with SDK 46. So is `@config-plugins/react-native-branch`, it depends on `@expo/config-plugins@"~4.1.4`.

**Comment by kbrandwijk** [comment]
Implemented in https://github.com/expo/config-plugins/pull/114
