### ISSUE TITLE
missing NSBluetoothPeripheralUsageDescription Info.plist key

### ISSUE THREAD

**Issue by mathiasnohall** [expo/config-plugins#12]
getting this error when trying to upload app to apple testflight for @config-plugins/react-native-ble-plx

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSBluetoothPeripheralUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data

**Comment by EvanBacon** [comment]
I see, it wasn't added to the docs: https://github.com/dotintent/react-native-ble-plx/issues/579

**Comment by EvanBacon** [comment]
Good to go in `0.0.1`, will need to update, and prebuild again to see the changes.
