### ISSUE TITLE
[react-native-branch] SDK 47 only builds for ios 13+ but podspec still has 12

### ISSUE THREAD

**Issue by Aryk** [expo/config-plugins#127]
### Summary

I believe we need to bump the ios version to 13 from 12.

<img width="1139" alt="Screen Shot 2022-11-08 at 6 31 56 PM" src="https://user-images.githubusercontent.com/525212/200723547-f9c9b88d-b591-483e-aac0-768cde67c6db.png">

### Config Plugin

@config-plugins/react-native-branch

### What platform(s) does this occur on?

iOS

### SDK Version

47

### Reproducible demo

Try building with eas 

```
  "react-native-branch": "^5.6.2",
    "@config-plugins/react-native-branch": "^3.0.0",
```

### Possible Solution

```diff
diff --git a/node_modules/@config-plugins/react-native-branch/ios/ExpoAdapterBranch.podspec b/node_modules/@config-plugins/react-native-branch/ios/ExpoAdapterBranch.podspec
index 83ef935..a0a6f42 100644
--- a/node_modules/@config-plugins/react-native-branch/ios/ExpoAdapterBranch.podspec
+++ b/node_modules/@config-plugins/react-native-branch/ios/ExpoAdapterBranch.podspec
@@ -10,7 +10,8 @@ Pod::Spec.new do |s|
   s.license        = package['license']
   s.author         = package['author']
   s.homepage       = package['homepage']
-  s.platform       = :ios, '12.0'
+  # Expo SDK 47 requires ios 13 and above.
+  s.platform       = :ios, '13.0'
   s.swift_version  = '5.4'
   s.source         = { git: 'https://github.com/expo/config-plugins.git' }
   s.static_framework = true

```

**Comment by felixliu226** [comment]
same issue happened...
I refered to [this answer](https://stackoverflow.com/questions/63686967/xcode-unit-test-compiling-for-ios-12-but-module-has-minimum-deployment-targe)
I changed Pods > ExpoModulesCore > Build Settings > iOS Deplyment Target to iOS 12.0, and it works on my local.

But when using eas build, it failed with the same error... Hope someone could help to fix this.

**Comment by jeffreybrowning** [comment]
Still happening

**Comment by Calvin-Octoco** [comment]
@jeffreybrowning did you upgrade to the latest plugin version? This fixed the issue for me.

**Comment by jeffreybrowning** [comment]
Will try so today -- I ended up removing branch from recent deploys rather than fight this.

**Comment by ebo7** [comment]
If anyone having trouble, turns out `expo upgrade` doesn't update this library but the plugin version 4 seems working for expo 47!

**Comment by Aryk** [comment]
Confirmed that it's upgrade to 13.0 on the latest plugin version, closing the ticket.
