### ISSUE TITLE
Broken Android builds with the react-native-branch plugin [SDK 48]

### ISSUE THREAD

**Issue by Noitham** [expo/config-plugins#168]
### Summary

I've noticed when adding the `@config-plugins/react-native-branch` plugin on my project, Android stops building.
The error thrown is the following:

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '.../android/app/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path=''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================
```

As soon as removing the `@config-plugins/react-native-branch` from the project & `app.cofing.ts` plugins list, it builds fine again and no errors are shown.

### Config Plugin

@config-plugins/react-native-branch

### What platform(s) does this occur on?

Android

### SDK Version

48

### Reproducible demo

Project using:

```
{
...
"expo": "~48.0.9",
"expo-build-properties": "~0.6.0",
"react-native-branch": "5.8.0"
...
}
```

1. Add `@config-plugins/react-native-branch@5.0.0`.
2. Setup plugin on `app.config.ts`
   1.  ```
        ['@config-plugins/react-native-branch',
        {
          apiKey: process.env.BRANCH_API_KEY,
          iosAppDomain: process.env.BRANCH_URL,
        }]
4. `expo prebuild`
5. `expo run:android` 💥

**Comment by Noitham** [comment]
When creating a reproducible repo I found out the issue, I'll close this as the plugin works as intended 👍 

The issue was apparently caused because we passed branch config in 2 ways.

`app.config.ts`

```
export default ({ config }: ConfigContext): ExpoConfig =>
  withPlugins(
    {
      ...config,
      android: {
          config: {
             branch: {
               apiKey: process.env.BRANCH_API_KEY,
             },
        },
      },
    },
    [
...
...
      [
        '@config-plugins/react-native-branch',
        {
          apiKey: BRANCH_API_KEY,
          iosAppDomain: BRANCH_URL,
        },
      ],
    ],
  );

```

Both on the plugin array and on the Android config object.
For some reason, this caused the error shown above.

**Comment by wolfdavo** [comment]
> 

Where did you set this? Having the same issue and struggling to resolve.
