### ISSUE TITLE
Add Expo SDK 50 support

### ISSUE THREAD

**Issue by mluiten** [expo/config-plugins#210]
### Summary

Yesterday Expo [released SDK 50](https://expo.dev/changelog/2024/01-18-sdk-50), but I'm getting peer dependency errors when combined with `@config-plugins` plugins, for example:

```
npm ERR! Conflicting peer dependency: expo@49.0.22
npm ERR! node_modules/expo
npm ERR!   peer expo@"^49" from @config-plugins/react-native-blob-util@6.0.0
npm ERR!   node_modules/@config-plugins/react-native-blob-util
npm ERR!     @config-plugins/react-native-blob-util@"^6.0.0" from the root project
```

When do you plan to add support for SDK 50? Thanks for the hard work!

### Config Plugin

@config-plugins/react-native-blob-util

### What platform(s) does this occur on?

Android, iOS

### SDK Version

50

### Reproducible demo

```
npm install expo@^50.0.0
npx expo install --fix
```

**Comment by oftoapp** [comment]
any update here?

**Comment by sebimarkgraf** [comment]
Seems to already have some progress over here: https://github.com/expo/config-plugins/pull/211

**Comment by sebimarkgraf** [comment]
Is this finished as https://github.com/expo/config-plugins/pull/220 is merged?
