### ISSUE TITLE
Expo Go Won't Run After Plug-in Install

### ISSUE THREAD

**Issue by yachtwave** [expo/config-plugins#227]
### Summary

I realize the Adjust plug-in wont run in Expo Go. However, Expo Go (with Simulator) will not run at all with the plugin is enabled in app.json the imports included in the project. I don't have this issue with other plugins (ex. sentry). The error I receive is below. Please help me with what I am doing wrong:

Invariant Violation: Your JavaScript code tried to access a native module that doesn't exist.
If you're trying to use a module that is not supported in Expo Go, you need to create a development build of your app. See https://docs.expo.dev/development/introduction/ for more info., js engine: hermes

### Config Plugin

@config-plugins/react-native-adjust

### What platform(s) does this occur on?

iOS

### SDK Version

50

### Reproducible demo

Error Message Listed Above

**Comment by b0iq** [comment]
https://github.com/expo/config-plugins/tree/main/packages/react-native-webrtc

**Comment by EvanBacon** [comment]
Config Plugins cannot be used with Expo Go, create a dev client. This is clearly documented in every plugin so no further action is needed.
