### ISSUE TITLE
android.enableDexingArtifactTransform.desugaring is deprecated

### ISSUE THREAD

**Issue by chanphiromsok** [expo/config-plugins#238]
### Summary

`android.enableDexingArtifactTransform.desugaring` is deprecated use `android.enableDexingArtifactTransform` instead
![image](https://github.com/expo/config-plugins/assets/65760336/4ca433a8-3089-462f-a211-9d20e2fa2cb9)

### Config Plugin

@config-plugins/react-native-webrtc

### What platform(s) does this occur on?

Android

### SDK Version

51

### Reproducible demo
npx expo prebuild
yarn android
android.enableDexingArtifactTransform.desugaring is deprecated 
![image](https://github.com/expo/config-plugins/assets/65760336/1a8738ca-2571-4782-8326-11f54ceeaa72)

**Comment by chanphiromsok** [comment]
since I dont see any modification in prebuild I decide to close 
![image](https://github.com/expo/config-plugins/assets/65760336/127f72a3-9f9b-477a-ae5d-14a37a9f1a31)

**Comment by brianMxBm** [comment]
Currently encountering this. Were you able to resolve this at all?

**Comment by brianMxBm** [comment]
It seems like it is modifying it in ```withDesurging.js```


```"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.withDesugaring = void 0;
const config_plugins_1 = require("expo/config-plugins");
/**
 * Set the `android.enableDexingArtifactTransform.desugaring` value in the static `gradle.properties` file.
 * This is used to disable desugaring to fix weird Android bugs. [Learn more](https://github.com/jitsi/jitsi-meet/issues/7911#issuecomment-714323255).
 */
const withDesugaring = (config, isDisabled) => {
    const desugaringKey = "android.enableDexingArtifactTransform.desugaring";
    return (0, config_plugins_1.withGradleProperties)(config, (config) => {
        config.modResults = config.modResults.filter((item) => {
            if (item.type === "property" && item.key === desugaringKey) {
                return false;
            }
            return true;
        });
        config.modResults.push({
            type: "property",
            key: desugaringKey,
            value: String(!isDisabled),
        });
        return config;
    });
};
exports.withDesugaring = withDesugaring;
```

**Comment by brianMxBm** [comment]
This was fixed in the new update.
