### ISSUE TITLE
[expo-52] @config-plugins/react-native-dynamic-app-icon breaking prebuild

### ISSUE THREAD

**Issue by mzaien** [expo/config-plugins#250]
### Summary

While testing expo 52 I got prebuild failing on me due to "@config-plugins/react-native-dynamic-app-icon" raising an issue 

```
PluginError: Failed to resolve plugin for module "@config-plugins/react-native-dynamic-app-icon" relative to "/Users/abdullah/...ect"
```

### Config Plugin

@config-plugins/react-native-dynamic-app-icon

### What platform(s) does this occur on?

iOS

### SDK Version

^52.0.0-preview.5

### Reproducible demo

https://github.com/mzaien/config-plugin-repro-expo-52

**Comment by JustJoostNL** [comment]
Same issue here.
