### ISSUE TITLE
ios 18 Build Failed (React Native PDF, New Architecure)

### ISSUE THREAD

**Issue by Arjit0762** [expo/config-plugins#254]
### Summary

The following build commands failed:
CompileC /Users/expo/Library/Developer/Xcode/DerivedData/ZoopDevelop-fgqtadscqcoewycwvmcbkgxxvcmh/Build/Intermediates.noindex/ArchiveIntermediates/ZoopDevelop/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/react-native-pdf.build/Objects-normal/arm64/RNPDFPdfView.o /Users/expo/workingdir/build/node_modules/react-native-pdf/ios/RNPDFPdf/RNPDFPdfView.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-pdf' from project 'Pods')
Archiving workspace ZoopDevelop with scheme ZoopDevelop
(2 failures)
Exit status: 65
+---------------------------------------+
| Build environment |
+-------------+-------------------------+
| xcode_path | /Applications/Xcode.app |
| gym_version | 2.225.0 |
| sdk | iPhoneOS18.1.sdk |

This is the error which I got while making a build in iOS (New Archtecture)
"expo": "^52.0.8",
"react-native": "0.76.2",
"react-native-pdf": "6.7.5",
"react-native-blob-util": "0.19.11",
"@config-plugins/react-native-blob-util": "8",
"@config-plugins/react-native-pdf": "8",

This is causing me blocker to move my app to new architecture

### Config Plugin

@config-plugins/react-native-pdf

### What platform(s) does this occur on?

iOS

### SDK Version

52

### Reproducible demo

build using eas build --profile development --platform ios

Build causing issue

**Comment by EvanBacon** [comment]
Looks like a bug with react-native-pdf, not the config plugin.
