### ISSUE TITLE
Expo 52 Android Error

### ISSUE THREAD

**Issue by alpha-adam** [expo/config-plugins#255]
### Summary

After migrating from Expo 51 to 52, I am getting runtime errors on the dev and prod build for android.

(NOBRIDGE) ERROR  Error: Exception in HostObject::get for prop 'RNCallKeep': com.facebook.react.internal.turbomodule.core.TurboModuleInteropUtils$ParsingException: Unable to parse @ReactMethod annotations from native module: RNCallKeep. Details: Module exports two methods to JavaScript with the same name: "displayIncomingCall [Component Stack]

### Config Plugin

@config-plugins/react-native-callkeep

### What platform(s) does this occur on?

Android

### SDK Version

52

### Reproducible demo

Build an Expo 52 project with react-native-callkeep and on launch there will be the runtime error.

**Comment by EvanBacon** [comment]
the config plugins are now updated for SDK 52

**Comment by alpha-adam** [comment]
Legend!
