### ISSUE TITLE
Support Adjust RN SDK ?

### ISSUE THREAD

**Issue by jetaix** [expo/config-plugins#35]
Do you plan to add a plugin for https://github.com/adjust/react_native_sdk ?

**Comment by EvanBacon** [comment]
Nope, PRs welcome.

- [Proguard example](https://github.com/expo/config-plugins/blob/master/packages/detox/src/withProguardGradle.ts).
- [iOS Frameworks example](https://github.com/expo/config-plugins/blob/6360360d942c4095337e5e9c950f3d874ae95672/packages/react-native-callkeep/src/withCallkeep.ts#L107-L114)
- [tracking permission example](https://github.com/expo/expo/blob/3a421c961a53ee523823d8fd18a6941f87868994/packages/expo-tracking-transparency/plugin/src/withTrackingTransparency.ts)
- [withSKAdNetworkIdentifiers](https://github.com/expo/expo/blob/master/packages/expo-facebook/plugin/src/withSKAdNetworkIdentifiers.ts)
- [dangerously adding google play services](https://github.com/expo/expo-cli/blob/c24263b4df40c4d592ff0c5b7b904f261f9a949a/packages/config-plugins/src/android/GoogleServices.ts)
