### ISSUE TITLE
how to absolute file path for using `fontfile`

### ISSUE THREAD

**Issue by tennispro7797** [expo/config-plugins#38]
I'm using `drawtext` and want to specify a custom font I have in my `/assets` directory. The problem is I don't know how to get the absolute filepath for this. 

I have tried setting my font directory using a relative path, but I assume that it requires an absolute path here as well.
```
    FFmpegKitConfig.setFontDirectoryList([
      "/system/fonts",
      "/System/Library/Fonts",
      "../../assets/fonts/",
    ]);
```

How do find the absolute path of an asset file in my app directory on a device?

**Comment by EvanBacon** [comment]
This question is better suited for the [upstream repo](https://github.com/tanersener/ffmpeg-kit).
