### ISSUE TITLE
App Clips 🙈

### ISSUE THREAD

**Issue by nandorojo** [expo/config-plugins#74]
### Library

https://twitter.com/Baconbrix/status/1513624269821026306?s=20&t=QaXZrtC98MrpIcZruc4TZw

### Summary

Shopify has discussed this, but I haven't seen a modern starter template.

### Any existing examples?

There is [this old starter](https://github.com/monterail/react-native-ios-app-clips) from [this blog post](https://adapptor.com.au/blog/creating-an-apple-app-clip-with-react-native).

**Comment by nandorojo** [comment]
ah, got it! would be awesome. good to know

**Comment by EvanBacon** [comment]
https://github.com/bndkt/react-native-app-clip/
